# Generated by Django 5.0.2 on 2024-02-18 10:50

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Resimler')),
            ],
            options={
                'verbose_name': 'Proje Resim',
                'verbose_name_plural': 'Projeye Ait Resimler',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Proje Adı')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Proje Resmi')),
                ('descriptions', tinymce.models.HTMLField(verbose_name='Proje Açıklaması')),
                ('type', models.CharField(max_length=50, verbose_name='Proje Türü')),
                ('location', models.CharField(max_length=50, verbose_name='Proje Konumu')),
                ('date', models.DateField(verbose_name='Proje Yapılma Tarihi')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='name')),
                ('projects_image', models.ManyToManyField(blank=True, to='projects.photos', verbose_name='Proje Resimleri')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
    ]
